void lettersnNumbers(char chr, int x1, int x2, int y1, int y2, int size, int R = 0, int G = 0, int B = 0);
void Capitalizer(char text[]);
void drawText(int size, int start_x, int start_y, int R, int G, int B, char text[], bool isNum = false, int num = 0);
void GiveNumASCII(int& num);
void DrawCursorMenu(int x, int y);
void DrawCursorBMenu(int x, int y);
void BoundaryMenu();
void LoadB();
void LoadT();
void NewGameB();
void NewGameT();
int Menu();